In [180]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [160]:
ranking = pd.read_csv('nba_rankings_2014-2020.csv', index_col=0)
ranking_df = pd.DataFrame(ranking)
ranking_df.reset_index(drop=True, inplace=True)
ranking_df.head()

,PLAYER,TEAM,AGE,SEASON,GP,W,L,MIN,PTS,FGM,...,AST,TOV,STL,BLK,PF,FP,DD2,TD3,+/-,rankings
0,Aaron Gordon,ORL,24,2019-20,62,30,32,32.5,14.4,5.4,...,3.7,1.6,0.8,0.6,2.0,31.9,20.0,1.0,-1.1,80.0
1,Aaron Holiday,IND,23,2019-20,66,42,24,24.5,9.5,3.5,...,3.4,1.3,0.8,0.2,1.8,19.3,3.0,0.0,1.7,76.0
2,Abdel Nader,OKC,26,2019-20,55,37,18,15.8,6.3,2.2,...,0.7,0.8,0.4,0.4,1.4,11.1,0.0,0.0,-1.5,71.0
3,Adam Mokoka,CHI,21,2019-20,11,3,8,10.2,2.9,1.1,...,0.4,0.2,0.4,0.0,1.5,5.5,0.0,0.0,4.5,68.0
4,Admiral Schofield,WAS,23,2019-20,33,9,24,11.2,3.0,1.1,...,0.5,0.2,0.2,0.1,1.5,6.3,0.0,0.0,-1.7,71.0

In [179]:
ranking_df = ranking_df.sort_values(by =['rankings'], ascending=False)
ranking_df.head()
top_df = ranking_df[:100]

In [162]:
X = top_df.copy()
X = X.drop("rankings", axis=1)
X = X.drop("TEAM", axis=1)
X = X.drop("PLAYER", axis=1)
X = X.drop("SEASON", axis=1)


X.head()

,AGE,GP,W,L,MIN,PTS,FGM,FGA,FG%,3PM,...,REB,AST,TOV,STL,BLK,PF,FP,DD2,TD3,+/-
1130,33,82,50,32,36.9,27.5,10.5,19.3,54.2,1.8,...,8.6,9.1,4.2,1.4,0.9,1.7,54.1,52.0,18.0,1.3
739,34,55,28,27,35.2,27.4,10.1,19.9,51.0,2.0,...,8.5,8.3,3.6,1.3,0.6,1.7,52.0,32.0,8.0,2.1
316,35,67,50,17,34.6,25.3,9.6,19.4,49.3,2.2,...,7.8,10.2,3.9,1.2,0.5,1.8,51.3,46.0,13.0,6.6
1109,29,68,49,19,34.2,26.4,9.3,18.0,51.6,2.5,...,6.8,5.4,3.0,0.7,1.8,2.0,47.0,15.0,2.0,5.2
709,28,60,41,19,34.0,26.6,9.3,18.8,49.6,1.9,...,7.3,3.3,2.0,1.8,0.4,1.5,44.8,14.0,0.0,5.9

In [163]:
y = top_df["rankings"].ravel()
y[:5]

array([98., 97., 97., 97., 97.])

In [165]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=4)

In [166]:
X_scaler = skl.preprocessing.StandardScaler()
X_scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [167]:
rf_model = RandomForestClassifier(n_estimators=128, random_state=4)

In [168]:
rf_model = rf_model.fit(X_train, y_train)

In [169]:
predictions = rf_model.predict(X_test)
predictions

array([90., 97., 90., 96., 89., 89., 90., 88., 90., 90., 89., 97., 88.,
       90., 96., 96., 94., 89., 90., 92., 89., 96., 89., 89., 90.])